apiVersion: v1
kind: Service
metadata:
  name: es
  labels:
    service: elasticsearch-discovery
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - port: 9200
    name: http
  - port: 9300
    name: transport
  selector:
    app: elasticsearch-logging
